/*
Drop table Hospital; --
Drop table Sellers; --
Drop table Aviaries; --
Drop table Employees; --
Drop table Offspring; --
Drop table Feed; --
Drop table Animal_Card;--
Drop table Animal; --
Drop table Animal_Employees; 
Drop table Animal_Menu;

select * from Sellers;
select * from Aviaries;
select * from Employees;
select * from Offspring;
select * from Hospital;
select * from Feed;
select * from Animal_Card;
select * from Animal;
select * from Animal_Employees;
select * from Animal_Menu;
*/
insert into Aviaries values (1, 1, 0);
insert into Aviaries values (2, 2, 1);
insert into Aviaries values (3, 2, 1);
insert into Aviaries values (4, 2, 1);
insert into Aviaries values (5, 3, 1);
insert into Aviaries values (6, 4, 0);
insert into Aviaries values (7, 4, 0);
insert into Aviaries values (8, 5, 0);
insert into Aviaries values (9, 6, 0);
insert into Aviaries values (10, 7, 1);
insert into Aviaries values (11, 7, 1);
insert into Aviaries values (12, 8, 1);
insert into Aviaries values (13, 8, 1);
insert into Aviaries values (14, 9, 0);
insert into Aviaries values (15, 10, 0);
insert into Aviaries values (16, 10, 0);
insert into Aviaries values (17, 11, 0);
insert into Aviaries values (18, 12, 1);
insert into Aviaries values (19, 12, 1);
insert into Aviaries values (20, 13, 0);
insert into Aviaries values (21, 14, 0);
insert into Aviaries values (22, 15, 0);
insert into Aviaries values (23, 15, 0);
insert into Aviaries values (24, 16, 1);
insert into Aviaries values (25, 16, 1);
insert into Aviaries values (26, 16, 1);
insert into Aviaries values (27, 17, 1);
insert into Aviaries values (28, 18, 1);
insert into Aviaries values (29, 18, 1);
insert into Aviaries values (30, 18, 1);
insert into Aviaries values (31, 19, 1);
insert into Aviaries values (32, 20, 1);
insert into Aviaries values (33, 20, 1);
insert into Aviaries values (34, 21, 1);
insert into Aviaries values (35, 22, 1);
insert into Aviaries values (36, 23, 1);
insert into Aviaries values (37, 24, 1);
insert into Aviaries values (38, 25, 1);
insert into Aviaries values (39, 26, 1);

insert into Sellers values ​​(1, 'Association "Soyuzpischeprom"', 'meat and fish', 'shellfish');
insert into Sellers values ​​(2, 'Association "Soyuzfoodprom"', 'live', 'insects');
insert into Sellers values ​​(3, 'Association "Soyuzpischeprom"', 'compound feed', 'compound feed for cattle');
insert into Sellers values ​​(4, 'Starch plant "SP Don"', 'vegetable', 'bran, seeds and others');
insert into Sellers values ​​(5, 'Starch plant "SP Don"', 'meat and fish', 'cattle carcasses');
insert into Sellers values ​​(6, 'Starch plant "SP Don"', 'meat and fish', 'carcasses of small and medium-sized animals');
insert into Sellers values ​​(7, 'TD "ZKM"', 'meat and fish', 'chicken meat and offal');
insert into Sellers values ​​(8, 'TD "ZKM"', 'meat and fish', 'pork meat and offal');
insert into Sellers values ​​(9, 'TD "ZKM"', 'meat and fish', 'beef meat and offal');
insert into Sellers values ​​(10, 'Domopet', 'feed', 'feed for pigs');
insert into Sellers values ​​(11, 'Domopet', 'feed', 'bird feed');
insert into Sellers values ​​(12, 'Domopet', 'compound feed', 'compound feed from fruits and berries');
insert into Sellers values ​​(13, 'ASC Feed', 'meat and fish', 'frozen fish and offal');
insert into Sellers values ​​(14, 'ASC Feed', 'vegetable', 'dried vegetables');
insert into Sellers values ​​(15, 'ASC Feed', 'vegetable', 'dried fruit');
insert into Sellers values ​​(16, 'Pet search', 'live', 'small rodents');
insert into Sellers values ​​(17, 'Pet search', 'live', 'lizards');
insert into Sellers values ​​(18, 'Pet search', 'live', 'frogs');
insert into Sellers values ​​(19, 'Petville', 'feed', 'feed for fur animals');
insert into Sellers values ​​(20, 'Petville', 'feed', 'dried insects');
insert into Sellers values ​​(21, 'Petville', 'meat and fish', 'eggs');
insert into Sellers values ​​(22, 'TM Amiri', 'live', 'small birds');
insert into Sellers values ​​(23, 'TM Amiri', 'live', 'young snakes');
insert into Sellers values ​​(24, 'TM Amiri', 'compound feed', 'dried larvae');
insert into Sellers values ​​(25, 'TM Esther', 'vegetable', 'seed mixtures');
insert into Sellers values ​​(26, 'TM Esther', 'vegetable', 'frozen fruit');
insert into Sellers values ​​(27, 'TM Esther', 'plant', 'flower nectar');
insert into Sellers values ​​(28, 'Zoo', 'vegetable', 'hay');
insert into Sellers values ​​(29, 'Zoo', 'vegetable', 'fruit juice');

insert into Employees values ​​(1, 'Ivanov', 'Ivan', 'Ivanovich', 'aquarist', 1);
insert into Employees values ​​(2, 'Petrov', 'Petr', 'Petrovich', 'aquarist', 1);
insert into Employees values ​​(3, 'Sidorova', 'Elena', 'Vladimirovna', 'veterinarian', 1);
insert into Employees values ​​(4, 'Smirnova', 'Anna', 'Sergeevna', 'veterinarian', 1);
insert into Employees values ​​(5, 'Kuznetsova', 'Olga', 'Alexandrovna', 'veterinarian', 1);
insert into Employees values ​​(6, 'Vasilieva', 'Maria', 'Igorevna', 'veterinarian-paramedic', 1);
insert into Employees values ​​(7, 'Popov', 'Alexey', 'Viktorovich', 'veterinarian-paramedic', 1);
insert into Employees values ​​(8, 'Nikolaev', 'Dmitry', 'Alexandrovich', 'animal technician', 0);
insert into Employees values ​​(9, 'Kozlova', 'Natalia', 'Sergeevna', 'zoologist', 1);
insert into Employees values ​​(10, 'Morozova', 'Ekaterina', 'Andreevna', 'zoologist', 1);
insert into Employees values ​​(11, 'Grigoriev', 'Maxim', 'Vladimirovich', 'zoopsychologist', 1);
insert into Employees values ​​(12, 'Orlova', 'Anna', 'Nikolaevna', 'zoopsychologist', 1);
insert into Employees values ​​(13, 'Belov', 'Vladimir', 'Ivanovich', 'ornithologist', 1);
insert into Employees values ​​(14, 'Denisov', 'Alexander', 'Alexandrovich', 'ornithologist', 1);
insert into Employees values ​​(15, 'Ivanov', 'Ivan', 'Ivanovich', 'animal feeding worker', 1);
insert into Employees values ​​(16, 'Petrov', 'Petr', 'Petrovich', 'animal feeding worker', 1);
insert into Employees values ​​(17, 'Sidorova', 'Elena', 'Vladimirovna', 'animal feeding worker', 1);
insert into Employees values ​​(18, 'Smirnova', 'Anna', 'Sergeevna', 'animal feeding worker', 1);
insert into Employees values ​​(19, 'Kuznetsova', 'Olga', 'Alexandrovna', 'zoo administration employee', 0);
insert into Employees values ​​(20, 'Vasilieva', 'Maria', 'Igorevna', 'zoo administration employee', 0);
insert into Employees values ​​(21, 'Popov', 'Alexey', 'Viktorovich', 'zoo administration employee', 0);
insert into Employees values ​​(22, 'Nikolaev', 'Dmitry', 'Alexandrovich', 'guardian of a zoological institution', 0);
insert into Employees values ​​(23, 'Kozlova', 'Natalia', 'Sergeevna', 'zoological institution guard', 0);
insert into Employees values ​​(24, 'Morozova', 'Ekaterina', 'Andreevna', 'zoological institution guard', 0);
insert into Employees values ​​(25, 'Grigoriev', 'Maxim', 'Vladimirovich', 'guardian of a zoological institution', 0);

insert into Offspring values (1, 0, 0, 'Born in the zoo', 0);
insert into Offspring values (2, 0, 0, null, 0);
insert into Offspring values (3, 4, 2, 'Born in the zoo', 1);
insert into Offspring values (4, 0, 0, null, 0);
insert into Offspring values (5, 0, 0, null, 0);
insert into Offspring values (6, 0, 0, null, 0);
insert into Offspring values (7, 6, 0, null, 0);
insert into Offspring values (8, 0, 0, null, 0);
insert into Offspring values (9, 0, 0, null, 0);
insert into Offspring values (10, 11, 0, 'Born in the zoo', 1);
insert into Offspring values (11, 0, 0, 'Born in the zoo', 0);
insert into Offspring values (12, 0, 0, null, 0);
insert into Offspring values (13, 12, 0, null, 0);
insert into Offspring values (14, 0, 0, 'Born in the zoo', 0);
insert into Offspring values (15, 0, 0, null, 0);
insert into Offspring values (16, 15, 0, 'Born in the zoo', 1);
insert into Offspring values (17, 0, 0, 'Born in the zoo', 0);
insert into Offspring values (18, 0, 0, null, 0);
insert into Offspring values (19, 18, 0, 'Born in the zoo', 1);
insert into Offspring values (20, 0, 0, null, 0);
insert into Offspring values (21, 0, 0, null, 0);
insert into Offspring values (22, 0, 0, 'Born in the zoo', 0);
insert into Offspring values (23, 22, 0, 'Born in the zoo', 1);
insert into Offspring values (24, 25, 26, 'Born in the zoo', 1);
insert into Offspring values (25, 0, 0, 'Born in the zoo', 0);
insert into Offspring values (26, 0, 0, null, 0);
insert into Offspring values (27, 0, 0, 'Born in the zoo', 0);
insert into Offspring values (28, 0, 0, null, 0);
insert into Offspring values (29, 28, 30, 'Born in the zoo', 1);
insert into Offspring values (30, 0, 0, null, 0);
insert into Offspring values (31, 0, 0, 'Born in the zoo', 0);
insert into Offspring values (32, 0, 0, null, 0);
insert into Offspring values (33, 32, 0, null, 0);
insert into Offspring values (34, 0, 0, null, 0);
insert into Offspring values (35, 0, 0, null, 0);
insert into Offspring values (36, 0, 0, null, 0);
insert into Offspring values (37, 0, 0, null, 0);
insert into Offspring values (38, 0, 0, null, 0);
insert into Offspring values (39, 0, 0, null, 0);
insert into Offspring values (40, 0, 0, null, 0);

insert into Hospital values (1, 4);
insert into Hospital values (2, 1);
insert into Hospital values (3, 1);
insert into Hospital values (4, 1);
insert into Hospital values (5, 1);
insert into Hospital values (6, 4);
insert into Hospital values (7, 4);
insert into Hospital values (8, 4);
insert into Hospital values (9, 4);
insert into Hospital values (10, 1);
insert into Hospital values (11, 1);
insert into Hospital values (12, 3);
insert into Hospital values (13, 3);
insert into Hospital values (14, 4);
insert into Hospital values (15, 2);
insert into Hospital values (16, 2);
insert into Hospital values (17, 2);
insert into Hospital values (18, 3);
insert into Hospital values (19, 3);
insert into Hospital values (20, 4);
insert into Hospital values (21, 4);
insert into Hospital values (22, 2);
insert into Hospital values (23, 2);
insert into Hospital values (24, 1);
insert into Hospital values (25, 1);
insert into Hospital values (26, 1);
insert into Hospital values (27, 1);
insert into Hospital values (28, 1);
insert into Hospital values (29, 1);
insert into Hospital values (30, 1);
insert into Hospital values (31, 1);
insert into Hospital values (32, 3);
insert into Hospital values (33, 3);
insert into Hospital values (34, 3);
insert into Hospital values (35, 3);
insert into Hospital values (36, 3);
insert into Hospital values (37, 3);
insert into Hospital values (38, 3);
insert into Hospital values (39, 3);
insert into Hospital values (40, 3);

insert into Feed values (1, 'meat and fish', 'shellfish', 'Polar bear');
insert into Feed values (2, 'live', 'insects', 'Ground squirrel');
insert into Feed values (3, 'compound feed', 'compound feed for cattle', 'Dik-dik');
insert into Feed values (4, 'vegetable', 'bran, seeds and others', 'Panda');
insert into Feed values (5, 'meat and fish', 'carcasses cattle', 'Honey badger');
insert into Feed values (6, 'meat and fish', 'carcasses of small and medium-sized animals', 'Jackal');
insert into Feed values (7, 'meat and fish', 'chicken meat and offal', 'Gray duck');
insert into Feed values (8, 'meat and fish', 'pork meat and offal', 'Mallard');
insert into Feed values (9, 'meat and fish', 'beef meat and by-products', 'Great-footed owl');
insert into Feed values (10, 'compound feed', 'compound feed for pigs', 'Siamese cobra');
insert into Feed values (11, 'compound feed', 'compound feed for poultry', 'Mainland Taipan');
insert into Feed values (12, 'compound feed', 'compound feed from fruits and berries', 'Salted mamba');
insert into Feed values (13, 'meat and fish', 'frozen fish and by-products', 'Coral adder');
insert into Feed values (14, 'vegetable', 'dried vegetables', 'Zebra lionfish');
insert into Feed values (15, 'vegetable', 'dried fruits', 'Mombasa lionfish');
insert into Feed values (16, 'live', 'small rodents', 'Green toad');
insert into Feed values (17, 'live', 'lizards', 'Mongolian toad');
insert into Feed values (18, 'live', 'frogs', 'Owl butterfly');
insert into Feed values (19, 'compound feed', 'compound feed for fur animals', 'Melpomene');
insert into Feed values (20, 'compound feed', 'dried insects', 'Peacock eye atlas');
insert into Feed values (21, 'meat and fish', 'eggs', 'African Achatina');
insert into Feed values (22, 'live', 'small birds', 'Arctic fox');
insert into Feed values (23, 'live', 'young snakes', 'Red parrot');
insert into Feed values (24, 'compound feed', 'dried larvae', 'Jungle cat');
insert into Feed values (25, 'vegetable', 'seed mixtures', 'Blue Ram');
insert into Feed values (26, 'vegetable', 'frozen fruits', 'Toque');
insert into Feed values (27, 'vegetable', 'flower nectar', 'Panda');
insert into Feed values (28, 'vegetable', 'hay', 'Honey badger');
insert into Feed values (29, 'vegetable', 'fruit juice', 'Jungle cat');

insert into Animal_Card values (1, 80, 120, 3, 'male', 0, null, 0, 1, 1, 0, 1, 1, 1, 1, 1);
insert into Animal_Card values (2, 15, 30, 5, 'female', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (3, 10, 25, 4, 'male', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (4, 11, 24, 4, 'female', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (5, 6, 40, 2, 'female', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (6, 4, 35, 1, 'male', 0, null, 1, 1, 1, 1, 1, 1, 1, 1, 1);
insert into Animal_Card values (7, 5, 30, 1, 'male', 0, null, 1, 1, 1, 1, 1, 1, 1, 1, 1);
insert into Animal_Card values (8, 1, 15, 1, 'male', 0, null, 1, 1, 1, 1, 1, 1, 1, 1, 1);
insert into Animal_Card values (9, 3, 30, 2, 'male', 0, null, 1, 1, 1, 1, 1, 1, 1, 1, 1);
insert into Animal_Card values (10, 12, 50, 4, 'female', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (11, 11, 45, 3, 'female', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (12, 1, 20, 1, 'male', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (13, 2, 25, 2, 'male', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (14, 2, 30, 1, 'male', 0, null, 1, 1, 1, 1, 1, 1, 1, 1, 1);
insert into Animal_Card values (15, 500, 150, 10, 'female', 0, null, 0, 1, 1, 0, 1, 1, 1, 1, 1);
insert into Animal_Card values (16, 400, 140, 8, 'female', 0, null, 1, 1, 1, 1, 1, 1, 1, 1, 1);
insert into Animal_Card values (17, 10, 40, 3, 'female', 0, null, 1, 1, 1, 1, 1, 1, 1, 1, 1);
insert into Animal_Card values (18, 1, 30, 2, 'male', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (19, 1.5, 35, 3, 'male', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (20, 2.5, 25, 2, 'male', 0, null, 1, 1, 1, 1, 1, 1, 1, 1, 1);
insert into Animal_Card values (21, 3.5, 30, 3, 'male', 0, null, 1, 1, 1, 1, 1, 1, 1, 1, 1);
insert into Animal_Card values (22, 1.5, 40, 2, 'female', 0, null, 1, 1, 1, 1, 1, 1, 1, 1, 1);
insert into Animal_Card values (23, 2, 45, 3, 'female', 0, null, 1, 1, 1, 1, 1, 1, 1, 1, 1);
insert into Animal_Card values (24, 3, 120, 5, 'female', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (25, 2.5, 110, 4, 'female', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (26, 2, 100, 3, 'female', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (27, 2.5, 150, 4, 'female', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (28, 2.5, 140, 4, 'female', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (29, 2.5, 140, 4, 'female', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (30, 2.5, 140, 4, 'female', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (31, 2.5, 100, 3, 'female', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (32, 1, 20, 1, 'male', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (33, 1.5, 25, 2, 'male', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (34, 2, 30, 2, 'male', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (35, 0.5, 5, 1, 'male', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (36, 0.7, 8, 1, 'male', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (37, 0.1, 3, 1, 'male', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (38, 0.2, 4, 1, 'male', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (39, 0.3, 5, 1, 'male', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);
insert into Animal_Card values (40, 0.5, 10, 1, 'male', 0, null, 0, 0, 0, 0, 0, 0, 0, 0, 0);

insert into Animal values (1, 'Panda', 'Moderate', 0, 1, 1, 1);
insert into Animal values (2, 'Honey badger', 'Hot', 1, 2, 2, 2);
insert into Animal values (3, 'Honey badger', 'Hot', 1, 3, 3, 3);
insert into Animal values (4, 'Honey badger', 'Hot', 1, 4, 4, 4);
insert into Animal values (5, 'Jungle cat', 'Hot', 1, 5, 5, 5);
insert into Animal values (6, 'Dik-dik', 'Moderate', 0, 6, 6, 6);
insert into Animal values (7, 'Dik-dik', 'Moderate', 0, 7, 7, 7);
insert into Animal values (8, 'Ground squirrel', 'Moderate', 0, 8, 8, 8);
insert into Animal values (9, 'Marmot', 'Moderate', 0, 9, 9, 9);
insert into Animal values (10, 'Jackal', 'Hot', 1, 10, 10, 10);
insert into Animal values (11, 'Jackal', 'Hot', 1, 11, 11, 11);
insert into Animal values (12, 'Toque', 'Hot', 0, 12, 12, 12);
insert into Animal values (13, 'Toque', 'Hot', 0, 13, 13, 13);
insert into Animal values (14, 'Blue Ram', 'Moderate', 0, 14, 14, 14);
insert into Animal values (15, 'Polar bear', 'Cold', 1, 15, 15, 15);
insert into Animal values (16, 'Polar bear', 'Cold', 1, 16, 16, 16);
insert into Animal values (17, 'Arctic fox', 'Cold', 1, 17, 17, 17);
insert into Animal values (18, 'Red parrot', 'Hot', 0, 18, 18, 18);
insert into Animal values (19, 'Red parrot', 'Hot', 0, 19, 19, 19);
insert into Animal values (20, 'Gray duck', 'Moderate', 0, 20, 20, 20);
insert into Animal values (21, 'Mallard', 'Moderate', 0, 21, 21, 21);
insert into Animal values (22, 'Great-footed owl', 'Moderate', 1, 22, 22, 22);
insert into Animal values (23, 'Great-footed owl', 'Moderate', 1, 23, 23, 23);
insert into Animal values (24, 'Siamese cobra', 'Hot', 1, 24, 24, 24);
insert into Animal values (25, 'Siamese cobra', 'Hot', 1, 25, 25, 25);
insert into Animal values (26, 'Siamese cobra', 'Hot', 1, 26, 26, 26);
insert into Animal values (27, 'Mainland Taipan', 'Hot', 1, 27, 27, 27);
insert into Animal values (28, 'Salted mamba', 'Hot', 1, 28, 28, 28);
insert into Animal values (29, 'Salted mamba', 'Hot', 1, 29, 29, 29);
insert into Animal values (30, 'Salted mamba', 'Hot', 1, 30, 30, 30);
insert into Animal values (31, 'Coral adder', 'Hot', 1, 31, 31, 31);
insert into Animal values (32, 'Zebra lionfish', 'Hot', 0, 32, 32, 32);
insert into Animal values (33, 'Zebra lionfish', 'Hot', 0, 33, 33, 33);
insert into Animal values (34, 'Mombasa lionfish', 'Hot', 0, 34, 34, 34);
insert into Animal values (35, 'Green toad', 'Wet', 0, 35, 35, 35);
insert into Animal values (36, 'Mongolian toad', 'Wet', 0, 36, 36, 36);
insert into Animal values (37, 'Owl butterfly', 'Hot', 0, 37, 37, 37);
insert into Animal values (38, 'Melpomene', 'Hot', 0, 38, 38, 38);
insert into Animal values (39, 'Peacock eye atlas', 'Hot', 0, 39, 39, 39);
insert into Animal values (40, 'African Achatina', 'Wet', 0, 40, 40, 40);

insert into Animal_Menu values (1, 'Panda', 'vegetable');
insert into Animal_Menu values (2, 'Honey badger', 'vegetable');
insert into Animal_Menu values (3, 'Honey badger', 'vegetable');
insert into Animal_Menu values (4, 'Honey badger', 'vegetable');
insert into Animal_Menu values (5, 'Jungle cat', 'vegetable');
insert into Animal_Menu values (6, 'Dik-dik', 'compound feed');
insert into Animal_Menu values (7, 'Dik-dik', 'compound feed');
insert into Animal_Menu values (8, 'Ground squirrel', 'live');
insert into Animal_Menu values (9, 'Marmot', 'compound feed');
insert into Animal_Menu values (10, 'Jackal', 'meat and fish');
insert into Animal_Menu values (11, 'Jackal', 'meat and fish');
insert into Animal_Menu values (12, 'Toque', 'vegetable');
insert into Animal_Menu values (13, 'Toque', 'vegetable');
insert into Animal_Menu values (14, 'Blue Ram', 'vegetable');
insert into Animal_Menu values (15, 'Polar bear', 'meat and fish');
insert into Animal_Menu values (16, 'Polar bear', 'meat and fish');
insert into Animal_Menu values (17, 'Arctic fox', 'live');
insert into Animal_Menu values (18, 'Red parrot', 'live');
insert into Animal_Menu values (19, 'Red parrot', 'live');
insert into Animal_Menu values (20, 'Gray duck', 'meat and fish');
insert into Animal_Menu values (21, 'Mallard', 'meat and fish');
insert into Animal_Menu values (22, 'Great-footed owl', 'meat and fish');
insert into Animal_Menu values (23, 'Great-footed owl', 'meat and fish');
insert into Animal_Menu values (24, 'Siamese cobra', 'compound feed');
insert into Animal_Menu values (25, 'Siamese cobra', 'compound feed');
insert into Animal_Menu values (26, 'Siamese cobra', 'compound feed');
insert into Animal_Menu values (27, 'Mainland Taipan', 'compound feed');
insert into Animal_Menu values (28, 'Salted mamba', 'compound feed');
insert into Animal_Menu values (29, 'Salted mamba', 'compound feed');
insert into Animal_Menu values (30, 'Salted mamba', 'compound feed');
insert into Animal_Menu values (31, 'Coral adder', 'meat and fish');
insert into Animal_Menu values (32, 'Zebra lionfish', 'vegetable');
insert into Animal_Menu values (33, 'Zebra lionfish', 'vegetable');
insert into Animal_Menu values (34, 'Mombasa lionfish', 'vegetable');
insert into Animal_Menu values (35, 'Green toad', 'live');
insert into Animal_Menu values (36, 'Mongolian toad', 'live');
insert into Animal_Menu values (37, 'Owl butterfly', 'live');
insert into Animal_Menu values (38, 'Melpomene', 'compound feed');
insert into Animal_Menu values (39, 'Peacock eye atlas', 'compound feed');
insert into Animal_Menu values (40, 'African Achatina', 'meat and fish');

insert into Animal_Employees values (1, 3, 'veterinarian', 1, 'Panda');
insert into Animal_Employees values (2, 3, 'veterinarian', 2, 'Honey badger');
insert into Animal_Employees values (3, 3, 'veterinarian', 3, 'Honey badger');
insert into Animal_Employees values (4, 6, 'veterinarian-paramedic', 4, 'Honey badger');
insert into Animal_Employees values (5, 4, 'veterinarian', 5, 'Jungle cat');
insert into Animal_Employees values (6, 4, 'veterinarian', 6, 'Dik-dik');
insert into Animal_Employees values (7, 4, 'veterinarian', 7, 'Dik-dik');
insert into Animal_Employees values (8, 7, 'veterinarian-paramedic', 8, 'Ground squirrel');
insert into Animal_Employees values (9, 5, 'veterinarian', 9, 'Marmot');
insert into Animal_Employees values (10, 5, 'veterinarian', 10, 'Jackal');
insert into Animal_Employees values (11, 5, 'veterinarian', 11, 'Jackal');
insert into Animal_Employees values (12, 6, 'veterinarian-paramedic', 12, 'Toque');
insert into Animal_Employees values (13, 3, 'veterinarian', 13, 'Toque');
insert into Animal_Employees values (14, 3, 'veterinarian', 14, 'Blue Ram');
insert into Animal_Employees values (15, 3, 'veterinarian', 15, 'Polar bear');
insert into Animal_Employees values (16, 6, 'veterinarian-paramedic', 16, 'Polar bear');
insert into Animal_Employees values (17, 4, 'veterinarian', 17, 'Arctic fox');
insert into Animal_Employees values (18, 4, 'veterinarian', 18, 'Red parrot');
insert into Animal_Employees values (19, 4, 'veterinarian', 19, 'Red parrot');
insert into Animal_Employees values (20, 7, 'veterinarian-paramedic', 20, 'Gray duck');
insert into Animal_Employees values (21, 5, 'veterinarian', 21, 'Mallard');
insert into Animal_Employees values (22, 5, 'veterinarian', 22, 'Great-footed owl');
insert into Animal_Employees values (23, 5, 'veterinarian', 23, 'Great-footed owl');
insert into Animal_Employees values (24, 6, 'veterinarian-paramedic', 24, 'Siamese cobra');
insert into Animal_Employees values (25, 3, 'veterinarian', 25, 'Siamese cobra');
insert into Animal_Employees values (26, 3, 'veterinarian', 26, 'Siamese cobra');
insert into Animal_Employees values (27, 3, 'veterinarian', 27, 'Mainland Taipan');
insert into Animal_Employees values (28, 6, 'veterinarian-paramedic', 28, 'Salted mamba');
insert into Animal_Employees values (29, 4, 'veterinarian', 29, 'Salted mamba');
insert into Animal_Employees values (30, 4, 'veterinarian', 30, 'Salted mamba');
insert into Animal_Employees values (31, 4, 'veterinarian', 31, 'Coral adder');
insert into Animal_Employees values (32, 7, 'veterinarian-paramedic', 32, 'Zebra lionfish');
insert into Animal_Employees values (33, 5, 'veterinarian', 33, 'Zebra lionfish');
insert into Animal_Employees values (34, 5, 'veterinarian', 34, 'Mombasa lionfish');
insert into Animal_Employees values (35, 5, 'veterinarian', 35, 'Green toad');
insert into Animal_Employees values (36, 6, 'veterinarian-paramedic', 36, 'Mongolian toad');
insert into Animal_Employees values (37, 3, 'veterinarian', 37, 'Owl butterfly');
insert into Animal_Employees values (38, 3, 'veterinarian', 38, 'Melpomene');
insert into Animal_Employees values (39, 3, 'veterinarian', 39, 'Peacock eye atlas');
insert into Animal_Employees values (40, 6, 'veterinarian-paramedic', 40, 'African Achatina');

insert into Animal_Employees values (41, 15, 'animal feeding worker', 1, 'Panda');
insert into Animal_Employees values (42, 15, 'animal feeding worker', 2, 'Honey badger');
insert into Animal_Employees values (43, 15, 'animal feeding worker', 3, 'Honey badger');
insert into Animal_Employees values (44, 15, 'animal feeding worker', 4, 'Honey badger');
insert into Animal_Employees values (45, 16, 'animal feeding worker', 5, 'Jungle cat');
insert into Animal_Employees values (46, 16, 'animal feeding worker', 6, 'Dik-dik');
insert into Animal_Employees values (47, 16, 'animal feeding worker', 7, 'Dik-dik');
insert into Animal_Employees values (48, 16, 'animal feeding worker', 8, 'Ground squirrel');
insert into Animal_Employees values (49, 17, 'animal feeding worker', 9, 'Marmot');
insert into Animal_Employees values (50, 17, 'animal feeding worker', 10, 'Jackal');
insert into Animal_Employees values (51, 17, 'animal feeding worker', 11, 'Jackal');
insert into Animal_Employees values (52, 17, 'animal feeding worker', 12, 'Toque');
insert into Animal_Employees values (53, 18, 'animal feeding worker', 13, 'Toque');
insert into Animal_Employees values (54, 18, 'animal feeding worker', 14, 'Blue Ram');
insert into Animal_Employees values (55, 18, 'animal feeding worker', 15, 'Polar bear');
insert into Animal_Employees values (56, 18, 'animal feeding worker', 16, 'Polar bear');
insert into Animal_Employees values (57, 15, 'animal feeding worker', 17, 'Arctic fox');
insert into Animal_Employees values (58, 15, 'animal feeding worker', 18, 'Red parrot');
insert into Animal_Employees values (59, 15, 'animal feeding worker', 19, 'Red parrot');
insert into Animal_Employees values (60, 15, 'animal feeding worker', 20, 'Gray duck');
insert into Animal_Employees values (61, 16, 'animal feeding worker', 21, 'Mallard');
insert into Animal_Employees values (62, 16, 'animal feeding worker', 22, 'Great-footed owl');
insert into Animal_Employees values (63, 16, 'animal feeding worker', 23, 'Great-footed owl');
insert into Animal_Employees values (64, 16, 'animal feeding worker', 24, 'Siamese cobra');
insert into Animal_Employees values (65, 17, 'animal feeding worker', 25, 'Siamese cobra');
insert into Animal_Employees values (66, 17, 'animal feeding worker', 26, 'Siamese cobra');
insert into Animal_Employees values (67, 17, 'animal feeding worker', 27, 'Mainland Taipan');
insert into Animal_Employees values (68, 17, 'animal feeding worker', 28, 'Salted mamba');
insert into Animal_Employees values (69, 18, 'animal feeding worker', 29, 'Salted mamba');
insert into Animal_Employees values (70, 18, 'animal feeding worker', 30, 'Salted mamba');
insert into Animal_Employees values (71, 18, 'animal feeding worker', 31, 'Coral adder');
insert into Animal_Employees values (72, 18, 'animal feeding worker', 32, 'Zebra lionfish');
insert into Animal_Employees values (73, 15, 'animal feeding worker', 33, 'Zebra lionfish');
insert into Animal_Employees values (74, 15, 'animal feeding worker', 34, 'Mombasa lionfish');
insert into Animal_Employees values (75, 15, 'animal feeding worker', 35, 'Green toad');
insert into Animal_Employees values (76, 15, 'animal feeding worker', 36, 'Mongolian toad');
insert into Animal_Employees values (77, 16, 'animal feeding worker', 37, 'Owl butterfly');
insert into Animal_Employees values (78, 16, 'animal feeding worker', 38, 'Melpomene');
insert into Animal_Employees values (79, 16, 'animal feeding worker', 39, 'Peacock eye atlas');
insert into Animal_Employees values (80, 16, 'animal feeding worker', 40, 'African Achatina');
